### ISSUE TITLE
File path issue

### ISSUE THREAD

**Issue by cpolera** [AdamWHY2K/Fa-apulu#1]
I tried to throw a PR up here for you to fix the file paths that are broken. You left a few in getName and bat_findLatest that still had @Resources instead of .. to go up a directory. 

Looks like you got this locked down as far as other people adding branches/PRs so I'm dropping you a line here

bat_findLatest:
lines 16, 51, 64, 67

bat_getName:
line 76

**Comment by cpolera** [comment]
You might actually want to change things to get the absolute path even since this runs from a .bat

**Comment by AdamWHY2K** [comment]
> Looks like you got this locked down as far as other people adding branches/PRs

Forgive me, I'm still figuring out github 😅

The files prepended with bat_ are intended to be run via Setup.bat only. Setup.bat is in the installation folder along with @Resources, so when Setup.bat launches the scripts they act as if they are in the same folder.

**Comment by cpolera** [comment]
Gotcha, I'd definitely recommend changing stuff over to use absolute paths. Then you wont need two versions of each.
